apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
  namespace: votre_namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votre_deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
