apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: example-vpa
  namespace: votre_namespace
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votre_deployment
  updatePolicy:
    updateMode: "Auto"
